add instructions for ssh key gen and config
curl-bash/curlbash pull request #6
Opened 2021-05-25 19:40 UTC by BRReed

Signed-off-by: Brian R Reed <b.r.reed@gmail.com>

2021-05-26 16:51 UTC, JoshRodstein commented on README.md
> +    2. Windows: `cat ~/.ssh/id_rsa.pub | ssh <USERNAME>@<SERVER-IP> "cat >> ~/.ssh/authorized_keys"`
This step fails from **windows** to **raspios** due to directory & file `~/.ssh/authorized_keys` non existing on the pi.

... manually creating the path on the pi fixes the issue

2021-05-26 16:53 UTC, JoshRodstein requested changes
comment left and changes requested for **ssh key**s step 2.2

2021-05-28 00:20 UTC, stephenlauck approved these changes

2021-05-28 00:20 UTC, stephenlauck commented on README.md
> +    2. Windows: `cat ~/.ssh/id_ed25519.pub | ssh <USERNAME>@<SERVER-IP> "cat > ~/.ssh/authorized_keys"`
dir must exists before copying key. @BRReed going to fix.

2021-05-28 00:21 UTC, JoshRodstein approved these changes

2021-05-28 00:21 UTC, JoshRodstein commented on README.md
> +    * Your public key is now saved at `~/.ssh/id_ed25519.pub` and the private key is at `~/.sssh/id_ed25519`
type  "sssh" should be ".ssh"

2021-05-28 00:50 UTC, merged